create index.html file
st-canpham/FE-Internship-Summer-2022_st-canpham_FE-Exercise pull request #3
Opened 2022-06-08 09:28 UTC by st-canpham

### Description
- Complete task create layout

2022-06-08 11:21 UTC, st-vantran commented on index.html
> +      <section class="section-offers">
Phần này trong banner

2022-06-08 11:21 UTC, st-vantran commented on index.html
> +        <div class="container">
List thì dùng ul li nhé

2022-06-08 11:21 UTC, st-vantran commented on index.html
> +                <p class="product-current-price">$89.99</p>
class sai tên rồi em: này là price-discount, current-price màu đen

2022-06-08 14:23 UTC, st-trangnguyen requested changes
Bài làm của em khá đẹp tuy nhiên còn thiếu những thứ sau nhé:

- Sử dụng thẻ chưa đúng: heading, a tel,....
- Chưa define đc grid system (row-col)
- Chưa define được các module có thể sử dụng ví dụ như btn.btn-primary, btn.btn-secondary hoặc badge, form-control,...
Em đọc thêm bootstrap

2022-06-08 14:23 UTC, st-trangnguyen commented on index.html
> +          <div class="banner-btn">
Rank B: banner-btn nhưng lại dùng thẻ `div` ???? 🔪

2022-06-08 14:23 UTC, st-trangnguyen commented on index.html
> +          <h2 class="section-title">Why should you choose us?</h2>
Rank B: Em cần chú ý thêm về cách dùng thẻ heading trong 1 page nhé

Text có chứa tên brand sẽ dùng h1 và 1 trang sẽ chỉ có duy nhất 1 h1
Text ở banner điểm nhấn sẽ là h2
Text ở các section title sẽ là h3
Text ở các title của list item sẽ là h4

2022-06-08 14:23 UTC, st-trangnguyen commented on index.html
> +          <ul class="section-content">
Rank B: 
class của ul nên là `xyz-list` vì dụ `product-list`
class của li nên là `xyz-item` ví dụ `product-item`
class a nên là `xyz-link` ví dụ `product-link`

phía trên của cái nav em làm tốt rồi, nên làm giống như vậy cho những phần khác

2022-06-09 15:04 UTC, st-trangnguyen requested changes

2022-06-10 02:43 UTC, st-trangnguyen requested changes

2022-06-10 02:43 UTC, st-trangnguyen commented on index.html
> +                <div class="offer">
clip ngoài cũng offer, clip trong cũng offer, là sao ba

2022-06-10 02:52 UTC, st-vantran approved these changes
LGTM!

2022-06-10 02:54 UTC, st-trangnguyen approved these changes
PR của em khá ổn rồi, vẫn còn 1 số chỗ cần lưu ý như ví dụ như những div bọc img là dư thừa,...
chị ví dụ block code dưới, em có thể xóa  `<div class="logo-img">` luôn. rút kinh nghiệm lần sau
```
            <h2 href="#" class="logo">
              <a href="" class="logo-link">
                <div class="logo-img">
                  <img src="" alt="logo E-Shop" />
                </div>
                <span>E-Shop</span>
              </a>
            </h2>```

2022-06-10 02:55 UTC, merged